name: Get raw page from Prior
run-name: Getting raw page data by the schedule, push it to master, scrap and sync to the cloud.
on: 
  workflow_dispatch:
  schedule:
    - cron: '5 8,11,14,17 * * *'
  push:
    branches:
      - neon-grafana
    
jobs:
  Parse-Materializations:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment
        run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: neon-grafana  # Ensure the neon-grafana branch is checked out
      - name : Check ckeckout
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: get raw content from prior  
        run: 
          python prior_get_content_gh.py
      - name: scrap raw and load data to the cloud 
        env: 
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: 
          echo $POSTGRES_PASSWORD
          python Raw2RatesCloud.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add prior_page*.html
          git commit  -m "Added raw page from Prior" 
      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master 
  
  
  
